#!/bin/bash

echo "🚀 Ollama 설치 스크립트"
echo "========================"
echo ""
echo "Ollama는 로컬에서 LLM을 실행할 수 있는 도구입니다."
echo "OpenAI API 없이 무료로 사용 가능합니다."
echo ""
echo "설치 방법:"
echo ""
echo "1. macOS (권장):"
echo "   curl -fsSL https://ollama.com/install.sh | sh"
echo ""
echo "   또는 Homebrew 사용:"
echo "   brew install ollama"
echo ""
echo "2. 설치 후 실행:"
echo "   ollama serve"
echo ""
echo "3. 모델 다운로드 (다른 터미널에서):"
echo "   ollama pull llama2:7b"
echo "   ollama pull nomic-embed-text"
echo ""
echo "4. 테스트:"
echo "   ollama run llama2:7b"
echo ""
echo "설치가 완료되면 실제 RAG 챗봇을 실행할 수 있습니다!"